### ISSUE TITLE
GLException on Ubuntu 16.04 (intel graphics)

### ISSUE THREAD

**Issue by miho** [miho/VRL-VCSG#2]
Caused by: com.jogamp.opengl.GLException: AWT-EventQueue-0: createImpl ARB n/a but required, profile > GL2 requested (OpenGL >= 3.1). Requested: GLProfile[GL3/GL4.hw], current: 3.0 (Compat profile, compat[ES2], FBO, hardware) - 3.0 Mesa 17.2.8
	at jogamp.opengl.x11.glx.X11GLXContext.createImpl(X11GLXContext.java:440)
	at jogamp.opengl.GLContextImpl.makeCurrentWithinLock(GLContextImpl.java:765)
	at jogamp.opengl.GLContextImpl.makeCurrent(GLContextImpl.java:648)
	at jogamp.opengl.GLContextImpl.makeCurrent(GLContextImpl.java:586)
	at com.jogamp.opengl.awt.GLJPanel$OffscreenBackend.initialize(GLJPanel.java:1731)
	... 81 more
Exception in thread "AWT-EventQueue-0" com.jogamp.opengl.GLException: Caught GLException: AWT-EventQueue-0: createImpl ARB n/a but required, profile > GL2 requested (OpenGL >= 3.1). Requested: GLProfile[GL3/GL4.hw], current: 3.0 (Compat profile, compat[ES2], FBO, hardware) - 3.0 Mesa 17.2.8
	at com.jogamp.opengl.awt.GLJPanel$OffscreenBackend.initialize(GLJPanel.java:1795)
	at com.jogamp.opengl.awt.GLJPanel.initializeBackendImpl(GLJPanel.java:1377)
	at com.jogamp.opengl.awt.GLJPanel.paintComponent(GLJPanel.java:549)
	at eu.mihosoft.vrl.vrljoglplugin.JOGLCanvas3D.paintComponent(JOGLCanvas3D.java:242)

**Comment by miho** [comment]
Seems to work now (tested on Ubuntu 16.04 and 18.04).
